name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.65.0.104.82 }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.ubuntu }}@${{ secrets.65.0.104.82 }} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          # any other deployment commands like:
          # npm install
          # pm2 restart app
        EOF

